### ISSUE TITLE
Old docs error message is inaccurate

### ISSUE THREAD

**Issue by timClicks** [canonical-websites/docs.jujucharms.com#12]
When visiting the documentation for an older version of Juju, e.g. https://docs.jujucharms.com/2.1/en/authors-subordinate-applications, users are presented with the following message:

> Caution! These older versions of Juju documentation are no longer maintained and are provided for reference only. See docs.jujucharms.com for the current, supported documentation. 

This is misleading because the user is already on docs.jujucharms.com.

**Comment by nottrobin** [comment]
This state will be fixed when the version from this repository goes live - hopefully on Monday. At that point URLs like the one above will redirect to old-docs.jujucharms.com.

**Comment by timClicks** [comment]
Thanks Robin 👷🏼‍♂️
